### ISSUE TITLE
Could not parse coloured lef

### ISSUE THREAD

**Issue by devarajulu** [trimcao/lef-parser#2]
Hi trimcao,
Am able to parse normal lef with this module without any issues,  but it is not able to parse coloured lef,
While parcing coloured lef , I am getting the following error.
It is an enhancement changes in lef.

# **ERROR:**
Start parsing LEF file...
Traceback (most recent call last):
  File "lef_parser.py", line 125, in <module>
    lef_parser.parse()
  File "lef_parser.py", line 52, in parse
    nextState = curState.parse_next(info)
  File "/proj/ipqa_dev/sw/play/tmp_rel/lef-parser-master/lef_util.py", line 197, in parse_next
    self.info["LAYER"][-1].add_rect(data)
  File "/proj/ipqa_dev/sw/play/tmp_rel/lef-parser-master/lef_util.py", line 271, in add_rect
    x0 = float(data[1])
ValueError: could not convert string to float: MASK

## Whats new in coloured lef ..?
-  MASK is a new attribute in **RECT** class

### Example:
PORT
      LAYER M1 ;
        RECT MASK 1 0.038 0.035 0.074 0.205 ;
END

## How to fix this issue ..?
File : lef_utils.py
The following block has to be update to resolve this issue.

    def add_rect(self, data):
        x0 = float(data[1])
        y0 = float(data[2])
        x1 = float(data[3])
        y1 = float(data[4])
        points = [(x0, y0), (x1, y1)]
        rect = Rect(points)
        self.shapes.append(rect)``

Regards,
Devarajulu.

**Comment by trimcao** [comment]
Hi Devarajulu,
I have abandoned this project long time ago. This is only a short-term project for me to understand the LEF and DEF file. Of course stuffs like colored LEF cannot work. You are welcome to use this code and improve upon it. 

Cheers.
